apiVersion: apps.mystic-06.github.io/v1alpha1
kind: QueueWorker
metadata:
  labels:
    app.kubernetes.io/name: queueworker-operator
    app.kubernetes.io/managed-by: kustomize
  name: queueworker-sample
spec:
  queueURL: "redis://redis-service:6379"
  minReplicas: 1
  maxReplicas: 10
  image: "nginx" # Using nginx just to test if the pod spawns
  tasksPerPod: 50
